### ISSUE TITLE
Needs instructions about how to deal with "ruff" - pretty much every python-related push always fails checks

### ISSUE THREAD

**Issue by gitcnd** [jimmo/git-and-micropython#2]
The list of weird and obscure "conventions" is impossible to manually code to (no trailing spaces, required commas with nothing after them on function definitions, splitting "sleep(0)" into 3 separate lines "sleep (\n\t0\n\t)", but only if there's a comment after it, double-spacing in comments, ...) and none of those conventions are enforced on any existing code: which means every time you fix anything, someone-elses code becomes "your problem" (because their non-convention code fails your PR checks)

Pretty much everyone is going to need to run some kind of tool to make code compliant.

Instructions telling us how to do that are needed.

And, on that topic, it might be better to add a section "How to prepare to contribute" and instead of giving us options and so forth, telling us exactly what to do, step-by-step. (the discussion about "origin" and usernames and example "git remote -v" are vastly too confusing): we need to be reading step-by-step things like "git clone" - and **not** a sentence like this:-

     This guide assumes you've already set up your fork and local clone, and have the "upstream" micropython/micropython repository as a remote named origin, and your fork as a second remote (e.g. named the same as your GitHub username).

And overall, as a newcomer to git, I feel that this guide is too confusing and relies too much on the user reading it already being a git expert: a quick revision to explain things better for new users would probably be a good idea.

The more you help us to get it right, the less work you ultimately have to do, right?

**Comment by jimmo** [comment]
> The list of weird and obscure "conventions"

These are pretty much the default rules enforced by `black` (and now `ruff`), and are standard to just about every Python project in existence. See https://peps.python.org/pep-0008/

> impossible to manually code to

I don't agree, but also the whole point of having "opinionated" formatters like `black` / `ruff` is that you don't have to. As already pointed out in https://github.com/micropython/micropython/issues/13433 you should make this run automatically (e.g. on-save hook in your editor, pre-commit for git, etc).

> none of those conventions are enforced on any existing code

Would need to see an example of this, as we run the formatter over the entire repo whenever we change config or version of the formatting tool. See e.g. https://github.com/micropython/micropython/pull/12805/commits/bbd8760bd9a2302e5abee29db279102bb11d7732 for a recent example. Possibly you're not using the right config (or the right tool?)

> Pretty much everyone is going to need to run some kind of tool to make code compliant.

Exactly.

> Instructions telling us how to do that are needed.

See https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md#code-auto-formatting

> the discussion about "origin" and usernames and example "git remote -v" are vastly too confusing

Unfortunately these are required concepts to contribute to any GitHub project. If you want to learn more, then https://git-scm.com/book/en/v2/ is probably the best place to start, as well as GitHub's quite extensive documentation -- I can't possibly be expected to write a complete guide to `git` and GitHub, my goal is just to provide a few recipes for the things that people are likely to encounter with our project (although many other projects use a nearly-identical workflow).

> we need to be reading step-by-step things 

People are welcome to submit PRs with improvements, but unfortunately unless I understand what the issues and conceptual hurdles people are running into it's very difficult to just intuit what exactly you need me to explain. As per 
https://github.com/jimmo/git-and-micropython#contributing if the advice here isn't working then please provide information about what you tried, what output you got, etc.

(Just a reminder, this is something I wrote in my spare time)
